Add S3 bucket initialization for angular frontend web app
WeatherAlertingSystem/WeatherAlerting-IaC pull request #2
Opened 2023-03-20 22:51 UTC by Bulduper

This MR contains:
- Create pulumi module with S3 bucket init
- Create web policy for the bucket

2023-03-22 19:11 UTC, bednarek-p requested changes

2023-03-22 19:11 UTC, bednarek-p commented on src/frontend_s3.py
> +        policy=(lambda path: open(path).read())("frontend_s3_policy.json"),
There is a dedicated data source to create policies in pulumi - `aws.iam.getPolicyDocument`.

Please take a look ([DOC LINK](https://www.pulumi.com/registry/packages/aws/api-docs/iam/getpolicydocument/)) and write a  separate function responsible for creating `frontend s3 policy`. This function should return JSON. You can do it like this:

```
aws.iam.get_policy_document(
.
.
.
.
).json
```


Then just simply apply the output of function to this parameter:

```
policy = create_s3_frontend_policy()
```

2023-03-22 19:11 UTC, bednarek-p commented on src/frontend_s3.py
> +        force_destroy=True,
I would like to have this parameter `force_destroy` to have different values depending on which environment we will work. On DEV I would like to have it as `True`, but on PROD `False`

Please read more about pulumi config variables - [DOC](https://www.pulumi.com/docs/intro/concepts/config/#code).

Example code:
```
frontend_config = pulumi.Config("frontend")
...
...
force_destroy = frontend_config.require_bool("s3_force_destroy")
```

It's just in case if in future we will have more environments than just DEV ;)

2023-03-22 19:11 UTC, bednarek-p commented on src/frontend_s3.py
> +        "163636840347-weather-alerting-frontend",
Please add `163636840347` to the configuration file as a variable. 

Read more about pulumi config variables - [DOC](https://www.pulumi.com/docs/intro/concepts/config/#code).

Then change every occurrence to the variable.

```
f"{account_id}-weather-alerting-frontend"
```

2023-03-22 19:11 UTC, bednarek-p commented on src/frontend_s3_policy.json
If you will change the way how we pass the policy (to `aws.iam.getPolicyDocument`). Then this file should be unnecessary. Remove it, please.

2023-03-22 19:11 UTC, bednarek-p commented on src/frontend_s3.py
> +# Create an AWS resource (S3 Bucket)
I think that we should make this a class -  `Frontend`. In future, this will aggregate all frontend resources in one class.

2023-03-26 19:45 UTC, Bulduper commented
I've done all the suggested changes. Additionally I added IAM resources for github automatic deployment to the pulumi stack.

2023-03-26 21:17 UTC, bednarek-p approved these changes
Very well 💪🏻

2023-03-26 21:21 UTC, merged